#ifndef THINGSPEAK_CONFIG_H
#define THINGSPEAK_CONFIG_H 

#define THINGSPEAK_API_KEY "DIN_API_KEY_HÄR" 
#define THINGSPEAK_CHANNEL_ID "DIN_CHANNEL_ID_HÄR" 

#define THINGSPEAK_HOST "api.thingspeak.com"
#define THINGSPEAK_PORT 80

//Max 1 vote every 30 second
#define THINGSPEAK_MIN_INTERVAL_MS 30000u

#endif
