#ifndef THINGSPEAK_CONFIG_H
#define THINGSPEAK_CONFIG_H 

#define THINGSPEAK_API_KEY "WK6TW5MX9IJU9SL1"
#define THINGSPEAK_CHANNEL_ID "3243824"

#define THINGSPEAK_HOST "api.thingspeak.com"
#define THINGSPEAK_PORT 80

//Max 1 vote every 30 second
#define THINGSPEAK_MIN_INTERVAL_MS 30000u

#endif
